apiVersion: v1
kind: Namespace
metadata:
  name: angkor-compliance
  labels:
    name: angkor-compliance
    app.kubernetes.io/name: angkor-compliance
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: platform
    app.kubernetes.io/part-of: compliance-management
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: angkor-compliance-quota
  namespace: angkor-compliance
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    services: "10"
    secrets: "20"
    configmaps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: angkor-compliance-limits
  namespace: angkor-compliance
spec:
  limits:
  - default:
      cpu: "1"
      memory: "2Gi"
    defaultRequest:
      cpu: "100m"
      memory: "256Mi"
    type: Container
  - max:
      storage: "50Gi"
    min:
      storage: "1Gi"
    type: PersistentVolumeClaim
